# Generated by Django 3.2.5 on 2021-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default=6959754126, max_length=10),
            preserve_default=False,
        ),
    ]
