# Generated by Django 3.2.5 on 2021-08-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210809_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='qty',
            new_name='quantity',
        ),
    ]
